---
title: "Statistics Using R - Probability"
author: "Fisher Ankney"
date: "9/9/2018"
output: html_document
---

### Chapter 3

```{r}
library('tidyverse')
```


#### Probability Distributions


Single die, showing the effect of sample size on the relative frequency
```{r}
single_die_1 <- sample(1:6, 100, replace=T)
sd_1_tab <- table(single_die_1)
sd_1_freq <- data_frame(num = 1:6, roll = sd_1_tab/100)

ggplot(sd_1_freq) + 
  geom_bar(aes(num,roll), stat="identity") + 
  geom_hline(yintercept = (1/6), col = "red", size=1) + 
  theme_minimal()

single_die_2 <- sample(1:6, 100000, replace=T)
sd_2_tab <- table(single_die_2)
sd_2_freq <- data_frame(num = 1:6, roll = sd_2_tab/100000)

ggplot(sd_2_freq) + 
  geom_bar(aes(num,roll), stat="identity") +
  geom_hline(yintercept = (1/6), col = "red", size=1) + 
  theme_minimal()
```

<br>




No no no, you can't just repeat the same thing, you'll have to use a loop
```{r}
# create empty dataframe of 100 values
roll_vector <- vector("double", 10000)


for (i in seq_along(roll_vector)) {
  roll_vector[i] = sum(sample(1:6,1), sample(1:6,1))
}

roll_vector

table(roll_vector)

roll_df <- as_data_frame(table(roll_vector)/10000)
colnames(roll_df) <- c("roll", "freq")
roll_df$roll <- as.numeric(roll_df$roll)

ggplot(roll_df) + 
  geom_bar(aes(roll, freq), stat="identity") +
  theme_minimal()
```

<br> 

make a function that rolls n number of dice and plots the results
```{r}
# function(n_dice, n_rolls) {

roll_em <- function(n_dice, n_roll) {

# Check for input errors, both inputs must be non-zero integers  
if (n_dice == 0 | is.na(n_dice) | n_dice %% 1 != 0) {
    stop("Enter a non-zero integer for the number of dice to roll")
} 
  else if (n_roll == 0 | is.na(n_roll) | n_roll %% 1 != 0) {
    stop("Enter a non-zero integer for the number of rolls to perform")
} 
  else {

  # create roll vector 
  roll_vector <- vector("double", n_roll)

  # set counter to zero
  i <- 0 

  # while loop 
  while (i <= length(roll_vector)) {
  
    dice_vector <- vector("double", n_dice)
    
    for (j in seq_along(dice_vector)) {
      dice_vector[j] = sample(1:6,1)
    }
    
    roll_vector[i] <- sum(dice_vector)
    
    i <- i + 1
  }

  roll_df <- as_data_frame(table(roll_vector)/n_roll)
  
  colnames(roll_df) <- c("roll", "freq")

  roll_df$roll <- as.numeric(roll_df$roll)

  ggplot(roll_df) + 
    geom_bar(aes(roll, freq), stat="identity") + 
    theme_minimal()
  }
}
```

test the roll_em function
```{r}
roll_em(5,200)
```

